<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: admin
 * Date: Thu, 26 Aug 2010 11:48:47 +0800
 */

$conf['title'] = 'kiwiguo';
$conf['start'] = 'kiwiguo';
$conf['lang'] = 'zh';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['ftp']['root'] = '/home/user/htdocs/kiwiguo';

// end auto-generated content
